### ISSUE TITLE
Android Crash

### ISSUE THREAD

**Issue by dylanvdmerwe** [NeutrinosPlatform/cordova-plugin-document-scanner#8]
document-scanner version 1.1.1

Crashing in an app with the following code:
```
  scanDocument() {
    // scan document using document-scanner from the camera
    scan.scanDoc(1, (imgUri) => {
      this.claimDocImage.imagePath = normalizeURL(imgUri);
    }, (err) => {
      console.error(err);
    });
  }
```

```    
    --------- beginning of crash
05-08 14:01:23.852 28011-28011/com.eightysixdegrees.antellogistics E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.eightysixdegrees.antellogistics, PID: 28011
    java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.eightysixdegrees.antellogistics-h9hhwnZVYDRxsfP_9H8p1g==/base.apk"],nativeLibraryDirectories=[/data/app/com.eightysixdegrees.antellogistics-h9hhwnZVYDRxsfP_9H8p1g==/lib/arm64, /data/app/com.eightysixdegrees.antellogistics-h9hhwnZVYDRxsfP_9H8p1g==/base.apk!/lib/arm64-v8a, /system/lib64]]] couldn't find "libopencv_java3.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:1011)
        at java.lang.System.loadLibrary(System.java:1657)
        at com.scanlibrary.Loader.load(Loader.java:14)
        at com.scanlibrary.ScanActivity.<clinit>(ScanActivity.java:125)
        at java.lang.Class.newInstance(Native Method)
        at android.app.Instrumentation.newActivity(Instrumentation.java:1174)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2669)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

```

Info:
```
global packages:

    cordova (Cordova CLI) : 8.0.0

local packages:

    @ionic/app-scripts : 3.1.8
    Cordova Platforms  : android 7.1.0 ios 4.5.4
    Ionic Framework    : ionic-angular 3.9.2

System:

    ios-deploy : 1.9.2
    ios-sim    : 6.1.2
    Node       : v8.11.1
    npm        : 5.8.0
    OS         : macOS High Sierra
    Xcode      : Xcode 9.3 Build version 9E145
```

**Comment by dylanvdmerwe** [comment]
Why would it not find `"libopencv_java3.so"`?

**Comment by dylanvdmerwe** [comment]
This crash is on Android in an existing project where I added the plugin. 

Other plugins used in this project:
```
code-push 2.0.4 "CodePushAcquisition"
cordova-plugin-appcenter-analytics 0.1.4 "App Center Analytics for Cordova"
cordova-plugin-appcenter-crashes 0.1.4 "App Center Crashes for Cordova"
cordova-plugin-appcenter-shared 0.1.3 "App Center shared code for Cordova"
cordova-plugin-camera 4.0.3 "Camera"
cordova-plugin-code-push 1.11.10 "CodePush"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-dialogs 2.0.1 "Notification"
cordova-plugin-document-scanner 1.1.1 "Scan"
cordova-plugin-file 6.0.1 "File"
cordova-plugin-geolocation 4.0.1 "Geolocation"
cordova-plugin-inappbrowser 2.0.2 "InAppBrowser"
cordova-plugin-ionic-keyboard 2.0.5 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 1.2.1 "cordova-plugin-ionic-webview"
cordova-plugin-network-information 2.0.1 "Network Information"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-sqlite-storage 2.3.1 "Cordova sqlite storage plugin"
phonegap-plugin-barcodescanner 7.1.2 "BarcodeScanner"
```

**Comment by dylanvdmerwe** [comment]
This one is concerning as I have no way to include this plugin to test in an existing project. What could be causing the exception? Is the plugin not installed correctly (i.e. libopencv_java3.so)?

**Comment by Varun-garg** [comment]
I have same issue, maybe [this](https://stackoverflow.com/questions/33943699/android-static-initialization-opencv-3-0-cannot-load-library-opencv-java3/38784665) can fix it

**Comment by Varun-garg** [comment]
Thanks, @ChrisTomAlx for quickly investigating the

**Comment by ChrisTomAlx** [comment]
[This](https://medium.com/mobiwise-blog/unsatisfiedlinkerror-problem-on-some-android-devices-b77f2f83837d) should work. Will be adding this to the plugin soon. In the meantime, if possible do let me know if this solution works in your apps. If it doesn't, I will try another route.

**Comment by ChrisTomAlx** [comment]
For some reason, I can't seem to recreate this issue on my end. Tested on quiet a few devices. Trying to succeed at failure is harder than I thought it would be.

Do let me know if you guys are having any luck at your end.

**Comment by Varun-garg** [comment]
Hi I am not good at gradle, and this config didn't work for me. Could you check it out.

```
allprojects {
	repositories {
		maven { 
			url 'https://jitpack.io' 
		}
	}
	
	defaultConfig {
	    
	    ndk {
		abiFilters "armeabi-v7a", "x86", "armeabi", "mips"
	    }
	    android.useDeprecatedNdk=true
	}
}

dependencies {
	compile 'com.github.NeutrinosPlatform:scanlibrary:master-SNAPSHOT'
}
```

Could not including the line be the cause?

    compile project(':scanlibrary')

**Comment by dylanvdmerwe** [comment]
I added the ndk stuff from the link above to my `build.gradle` file and the app no longer crashes which is very promising!

`        
    defaultConfig {
        versionCode cdvVersionCode ?: new BigInteger("" + privateHelpers.extractIntFromManifest("versionCode"))
        applicationId privateHelpers.extractStringFromManifest("package")

        if (cdvMinSdkVersion != null) {
            minSdkVersion cdvMinSdkVersion
        }

        ndk {
            abiFilters "armeabi-v7a", "x86", "armeabi", "mips"
        }
    }
`

**Comment by Varun-garg** [comment]
hey @dylanvdmerwe  could you send your full `build.gradle`?

**Comment by dylanvdmerwe** [comment]
![image](https://user-images.githubusercontent.com/2852839/40306932-d70da93e-5d00-11e8-875b-197b6492b744.png)


Here it is as a text file. Not sure if it helps or not. 
[build.gradle.txt](https://github.com/NeutrinosPlatform/cordova-plugin-document-scanner/files/2022447/build.gradle.txt)

**Comment by dylanvdmerwe** [comment]
Awesome news. @ChrisTomAlx how do we get this change into the plugin so it's setup on adding of the plugin?

**Comment by ChrisTomAlx** [comment]
@dylanvdmerwe @Varun-garg Awesome!! Thanks for the help guys. I will implement this into the plugin now. Will get back to you once its done.

**Comment by ChrisTomAlx** [comment]
I have made changes to the library, but like I said, I wasn't able to test it. If you guys get the time please do test it out and let me know.

**Comment by dylanvdmerwe** [comment]
Let me know when I can test @ChrisTomAlx. I'm not seeing any commits.

**Comment by ChrisTomAlx** [comment]
@dylanvdmerwe I am making edits to the library. It did not work and so will be reverting back and looking for a new route to add this to the plugin. If all else fails will update documentation.

**Comment by ChrisTomAlx** [comment]
@dylanvdmerwe I have made the necessary edits to the library, allowing it to use 32 bit builds. You won't see commits in the plugin. The plugin has the library has a dependency. I tested it out on my end with no problems. But I don't think it helps since my device is not using a 64 bit build. Please feel free to test it on your 64 bit device when you get the time.
 
If you run into issues, i will see what else can be done. 

Thank you for taking the time to help us. Really appreciate it.

Oh here is the [link](https://github.com/NeutrinosPlatform/scanlibrary) to the library we are using in the plugin, if you guys need it. I have credited the original authors in my readme (You can get the link to the original library there).

**Comment by dylanvdmerwe** [comment]
@ChrisTomAlx I am not able to build now:

![image](https://user-images.githubusercontent.com/2852839/40426755-2b6d532a-5e9c-11e8-8d6f-c29b2a58c3fe.png)

**Comment by dylanvdmerwe** [comment]
I have just removed my platform and plugins folder and readded android@7.1.0.

The app crashes with the following error:
```
05-23 15:48:19.048 26908-26908/com.eightysixdegrees.antellogistics E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.eightysixdegrees.antellogistics, PID: 26908
    java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.eightysixdegrees.antellogistics-7zZ3PioI3GBjlWh0dOJ6Yw==/base.apk", zip file "/data/app/com.eightysixdegrees.antellogistics-7zZ3PioI3GBjlWh0dOJ6Yw==/split_lib_dependencies_apk.apk", zip file "/data/app/com.eightysixdegrees.antellogistics-7zZ3PioI3GBjlWh0dOJ6Yw==/split_lib_slice_0_apk.apk", zip file "/data/app/com.eightysixdegrees.antellogistics-7zZ3PioI3GBjlWh0dOJ6Yw==/split_lib_slice_1_apk.apk", zip file "/data/app/com.eightysixdegrees.antellogistics-7zZ3PioI3GBjlWh0dOJ6Yw==/split_lib_slice_2_apk.apk", zip file "/data/app/com.eightysixdegrees.antellogistics-7zZ3PioI3GBjlWh0dOJ6Yw==/split_lib_slice_3_apk.apk", zip file "/data/app/com.eightysixdegrees.antellogistics-7zZ3PioI3GBjlWh0dOJ6Yw==/split_lib_slice_4_apk.apk", zip file "/data/app/com.eightysixdegrees.antellogistics-7zZ3PioI3GBjlWh0dOJ6Yw==/split_lib_slice_5_apk.apk", zip file "/data/app/com.eightysixdegrees.antellogistics-7zZ3PioI3GBjlWh0dOJ6Yw==/split_lib_slice_6_apk.apk", zip file "/data/app/com.eightysixdegrees.antellogistics-7zZ3PioI3GBjlWh0dOJ6Yw==/split_lib_slice_7_apk.apk", zip file "/data/app/com.eightysixdegrees.antellogistics-7zZ3PioI3GBjlWh0dOJ6Yw==/split_lib_slice_8_apk.apk", zip file "/data/app/com.eightysixdegrees.antellogistics-7zZ3PioI3GBjlWh0dOJ6Yw==/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.eightysixdegrees.antellogistics-7zZ3PioI3GBjlWh0dOJ6Yw==/lib/arm64, /data/app/com.eightysixdegrees.antellogistics-7zZ3PioI3GBjlWh0dOJ6Yw==/base.apk!/lib/arm64-v8a, /data/app/com.eightysixdegrees.antellogistics-7zZ3PioI3GBjlWh0dOJ6Yw==/split_lib_dependencies_apk.apk!/lib/arm64-v8a, /data/app/com.eightysixdegrees.antellogistics-7zZ3PioI3GBjlWh0dOJ6Yw==/split_lib_slice_0_apk.apk!/lib/arm64-v8a, /data/app/com.eightysixdegrees.antellogistics-7zZ3PioI3GBjlWh0dOJ6Yw==/split_lib_slice_1_apk.apk!/lib/arm64-v8a, /data/app/com.eightysixdegrees.antellogistics-7zZ3PioI3GBjlWh0dOJ6Yw==/split_lib_slice_2_apk.apk!/lib/arm64-v8a, /data/app/com.eightysixdegrees.antellogistics-7zZ3PioI3GBjlWh0dOJ6Yw==/split_lib_slice_3_apk.apk!/lib/arm64-v8a, /data/app/com.eightysixdegrees.antellogistics-7zZ3PioI3GBjlWh0dOJ6Yw==/split_lib_slice_4_apk.apk!/lib/arm64-v8a, /data/app/com.eightysixdegrees.antellogistics-7zZ3PioI3GBjlWh0dOJ6Yw==/split_lib_slice_5_apk.apk!/lib/arm64-v8a, /data/app/com.eightysixdegrees.antellogistics-7zZ3PioI3GBjlWh0dOJ6Yw==/split_lib_slice_6_apk.apk!/lib/arm64-v8a, /data/app/com.eightysixdegrees.antellogistics-7zZ3PioI3GBjlWh0dOJ6Yw==/split_lib_slice_7_apk.apk!/lib/arm64-v8a, /data/app/com.eightysixdegrees.antellogistics-7zZ3PioI3GBjlWh0dOJ6Yw==/split_lib_slice_8_apk.apk!/lib/arm64-v8a, /data/app/com.eightysixdegrees.antellogistics-7zZ3PioI3GBjlWh0dOJ6Yw==/split_lib_slice_9_apk.apk!/lib/arm64-v8a, /system/lib64]]] couldn't find "libopencv_java3.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:1011)
        at java.lang.System.loadLibrary(System.java:1657)
        at com.scanlibrary.Loader.load(Loader.java:14)
        at com.scanlibrary.ScanActivity.<clinit>(ScanActivity.java:125)
        at java.lang.Class.newInstance(Native Method)
        at android.app.Instrumentation.newActivity(Instrumentation.java:1174)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2669)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

**Comment by Varun-garg** [comment]
Yup, It crashed!

**Comment by Varun-garg** [comment]
Again, adding the following in plugins `build.gradle` fixed it.
```

android {
	defaultConfig {
		versionCode cdvVersionCode ?: new BigInteger("" + privateHelpers.extractIntFromManifest("versionCode"))
		applicationId privateHelpers.extractStringFromManifest("package")

		if (cdvMinSdkVersion != null) {
		    minSdkVersion cdvMinSdkVersion
		}

		ndk {
		    abiFilters "armeabi-v7a", "x86", "armeabi", "mips"
		}
	}
}
```

**Comment by ChrisTomAlx** [comment]
I guess a 64 bit build is the way to go now. Will be closing this issue after adding this info to the documentation and a 64 bit build will be added to the future enhancement plans. 

Thank you guys for all the help!

**Comment by ChrisTomAlx** [comment]
Hey guys just letting you know this issue has been permanently fixed as of #24 . No workaround is required now. Please let me know if you run into any other troubles or if the fix doesn't work for you.

Cheers and have a nice day :)
[Chris](https://github.com/ChrisTomAlx)
[Neutrinos](http://www.neutrinos.co/)

**Comment by dylanvdmerwe** [comment]
Note that I still have to edit the gradle file otherwise this crashes. Retested on version 2.0.1.

**Comment by ChrisTomAlx** [comment]
Added 64 bit architectures to the scan library. Should be permanently fixed now!

Cheers,
[Chris](https://github.com/ChrisTomAlx)
[Neutrinos](http://www.neutrinos.co/)

**Comment by dylanvdmerwe** [comment]
@ChrisTomAlx I have just cloned one of my projects and added android as a platform from scratch (deleted plugins folder) and when I run `ionic cordova run android` on a device, the crash still persists. Version 2.0.1 of the `cordova-plugin-document-scanner` plugin.

In Android Studio you still need to edit the gradle file as per my instructions above to prevent the crash. 

Maybe I am missing something?

**Comment by ChrisTomAlx** [comment]
Released version 2.0.2. Could you let me know if you are still facing this issue in this version?

Cheers,
[Chris](https://github.com/ChrisTomAlx)
[Neutrinos](http://www.neutrinos.co/)
